### ISSUE TITLE
Issue:  Cube cropping/cutting behavior

### ISSUE THREAD

**Issue by rshuping** [darioflute/sospex#19]
When cutting/cropping a cube, you have to save the result and then *load* the saved cube to start using it.  This was a little confusing as most applications (and even the masking feature in SOSPEX) dont work that way:  the data are altered first and then user is given option to save.  If this can't be changed, then I would suggest emphasizing this sequence in the tutorials.

**Comment by darioflute** [comment]
After trimming or cropping  a cube, the new version is uploaded automatically starting from version 0.30.beta
