### ISSUE TITLE
instruction to install sospex

### ISSUE THREAD

**Issue by JeongheeRho** [darioflute/sospex#3]
Instruction to install SOSPEX
1.	Download anaconda from https://www.anaconda.com/download/#macos
     The file is “Anaconda3-5.0.1-MacOSX-x86_64.sh” for mac
2.	>./Anaconda3-5.0.1-MacOSX-x86_64.sh (run the script)
  This command will create /Users/username/anaconda3 directory
3.	Add the path in .cshrc
Here is an example of command in tshell (in the file of .cshrc)
       # Added for anaconda 3
       setenv PATH "/Users/usernam/anaconda3/bin:$PATH"
4.	Verify that you have python3. 
>which python
  /Users/jrho/anaconda3/bin/python
   Python 3.6.3 |Anaconda custom (64-bit)| (default, Oct  6 2017, 12:04:38) 
5.	Type “sospex” to start the program
> sospex
libpng warning: iCCP: known incorrect sRGB profile
QBasicTimer::start: QBasicTimer can only be used with threads started with QThread
6.	Reinstall the program
>conda install -c darioflute sospex
[sofiasospexscript.txt](https://github.com/darioflute/sospex/files/1602190/sofiasospexscript.txt)
[sofiasospexscript.txt](https://github.com/darioflute/sospex/files/1602192/sofiasospexscript.txt)

**Comment by darioflute** [comment]
Maybe I can add a section in the README. But this is more about installing anaconda
which is documented already in their page.

**Comment by darioflute** [comment]
Instructions added on the tutorials on github
