### ISSUE TITLE
Issue with new matplotlib

### ISSUE THREAD

**Issue by wanggilim** [darioflute/sospex#33]
After updating all python libraries, I could not run sospex with an error message - TypeError: register_cmap() got an unexpected keyword argument 'data'.
As of Dr. Fadda's recommendation, this has been resolved once regressing matplotlib to older version.

**Comment by darioflute** [comment]
The problem has been fixed. It is now possible to run sospex with matplotlib 3.4.2
A new anaconda distribution will be uploaded soon.
