### ISSUE TITLE
Long-term implementaion request

### ISSUE THREAD

**Issue by JeongheeRho** [darioflute/sospex#6]
Here I put the requests which can be implemented when you have a chance.
1) Add zoom in and out option in the spectrum window. I note that the image window has an option to zoom in and out by touching the keyboard pad. I know you have zooming option with the logo by highlighting the boundary in the window.
2) Add the cursor reading of pixel number (x,y) and/or coordinate (ra,dec) when you move around the cursor. I note sospex already has this option for the spectrum window. As I move the cursor, it gives x and y values. That is nice. This can apply to the image window.

**Comment by JeongheeRho** [comment]
For the item 2 above, maybe you can add the value of the position as well. 
(x,y,value) or (ra,dec,value) where value is Jy, Jy/arcsec, or MJy/sr,

**Comment by darioflute** [comment]
The implementation of the cursor position is done automatically through the navigationtoolbar.
These addition will require a lot more code.

**Comment by JeongheeRho** [comment]
The cursor position function is very nice. I can do really science now.

3) add a function to make grid maps of spectra for a selected region. For example, show 3x3 spectra (or 10x10 spectra etc).

Thanks.
