### ISSUE TITLE
Comments on 0.16.beta version

### ISSUE THREAD

**Issue by JeongheeRho** [darioflute/sospex#7]
A lot of improvements. It is very nice.

1) When I downloaded the image (for example of WISE), it did not appear; you can implement this later.

I also note you delete issues. I think it is better to leave them. You can close the issue when you are done. That way you can see the history of sospex, which people can look at in future.
I will add more later..

**Comment by darioflute** [comment]
Apparently this is a problem with mac os-x sierra, not with el capitan.
Need to investigate.

**Comment by JeongheeRho** [comment]
When I save an ascii file of a spectrum, the flux and uncorrected flux (column 2 and 3) have the identical number. The figure seems to show different numbers though. (Feb. 4, 2018)

**Comment by JeongheeRho** [comment]
When I put a cursor on the image, it shows wcs coordinate, which is very nice. Can you add also x,y coordinate so I can compare with those in fluxer or array in the cube?

**Comment by darioflute** [comment]
Thanks for spotting the bug. In the next version, the uncorrected flux will be saved. 
Also, x and y coordinates cannot be displayed in the same way as the coordinates. I will implement
a way to check the x,y coordinate with a mouse click.

**Comment by darioflute** [comment]
The changes have been implemented. They will appear in the next anaconda version.

**Comment by JeongheeRho** [comment]
Dario,
I just let you know that I am off this week. Am at Washington DC and go to New York with my daughter for colleage tour and sightseeing.
See you next week.
Jeonghee

**Comment by darioflute** [comment]
OK,
enjoy the college tour !
Cheers,
Dario
